### ISSUE TITLE
Depency on clojure.contrib 1.2.0 seems out of date

### ISSUE THREAD

**Issue by jconti** [drone29a/clojure-twitter#14]
=> (require 'twitter)
Warning: _print-pretty_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-pretty_ or change the name. (clojure/contrib/pprint/pprint_base.clj:29)
Warning: _print-pprint-dispatch_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-pprint-dispatch_ or change the name. (clojure/contrib/pprint/pprint_base.clj:33)
Warning: _print-pprint-dispatch_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-pprint-dispatch_ or change the name. (clojure/contrib/pprint/pprint_base.clj:33)
Warning: _print-right-margin_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-right-margin_ or change the name. (clojure/contrib/pprint/pprint_base.clj:38)
Warning: _print-miser-width_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-miser-width_ or change the name. (clojure/contrib/pprint/pprint_base.clj:44)
Warning: _print-lines_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-lines_ or change the name. (clojure/contrib/pprint/pprint_base.clj:51)
Warning: _print-circle_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-circle_ or change the name. (clojure/contrib/pprint/pprint_base.clj:56)
Warning: _print-shared_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-shared_ or change the name. (clojure/contrib/pprint/pprint_base.clj:61)
Warning: _print-suppress-namespaces_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-suppress-namespaces_ or change the name. (clojure/contrib/pprint/pprint_base.clj:65)
Warning: _print-radix_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-radix_ or change the name. (clojure/contrib/pprint/pprint_base.clj:72)
Warning: _print-base_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _print-base_ or change the name. (clojure/contrib/pprint/pprint_base.clj:78)
Warning: _current-level_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _current-level_ or change the name. (clojure/contrib/pprint/pprint_base.clj:89)
Warning: _current-length_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _current-length_ or change the name. (clojure/contrib/pprint/pprint_base.clj:91)
Warning: _format-str_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _format-str_ or change the name. (clojure/contrib/pprint/cl_format.clj:64)
CompilerException java.lang.IllegalStateException: Can't dynamically bind non-dynamic var: clojure.contrib.pprint/_format-str_, compiling:(dispatch.clj:90)

**Comment by atroche** [comment]
I'm also having this problem. What's an easy fix?

**Comment by jconti** [comment]
Well, I moved on to https://github.com/adamwynne/twitter-api, which I've had a nice experience with while making a little site (http://www.javatechboise.org).

**Comment by drone29a** [comment]
jconti: Sorry, not sure how I missed this.  That issue was fixed months ago (a year ago?) but apparently I didn't push a new release or you didn't update the lib.  Glad you found something that works for you.

atroche: Check out 1.2.8 ([clojure-twitter "1.2.8"]), just pushed to clojars.  I occasionally use the library for data collection, but please let me know if you run into any issues.

**Comment by jconti** [comment]
Thank you for the update.  I will try this again when I get the chance.
