### ISSUE TITLE
problem on GAE

### ISSUE THREAD

**Issue by denlab** [drone29a/clojure-twitter#4]
Hi, 

Great lib, works fine locally. But when deployed on GAE, https doesn't works (javax.net.ssl.HttpsURLConnection is a restricted class).
So I swiched to regular http: 

  (twitter/with-oauth

instead of : 

  (twitter/with-https
    (twitter/with-oauth

In fact even if I only :require the twitter lib without using it, it breaks.

Here's the stacktrace: https://gist.github.com/973086

A solution could be to use HttpConnection instead of HttpsConnection, the former is on the GAE whitelist.

Any hints ? 

thx

Denis

**Comment by denlab** [comment]
I forgot: even with regular http it still breaks, as if httpsconnection was loaded anyway

**Comment by drone29a** [comment]
This I'm going to fix by changing how the lib works.  The lib should allow you to inject your own base fetch function.  Are you able to hack up a workaround in the meantime?

**Comment by denlab** [comment]
Well the workaround was to fall back to using a java lib (shame on me! :)
It's twitter4j, it is GAE-proof, and I needed 2 lines to call it: 

(:import (twitter4j TwitterFactory Query)))

;; raw results from twitter
(def raw-results (.search (.getInstance (TwitterFactory.))
                          (Query. "#sfeir")))

see: https://github.com/denlab/twitalyse/blob/master/src/twitalyse/twitter.clj

Denis

**Comment by drone29a** [comment]
Heh, glad you got something working.  Until I get to the refactor I mentioned above, twitter4j is a good alternative.
